# Generated by Django 4.0.2 on 2022-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('due_date', models.DateTimeField(verbose_name='Due date')),
                ('complete', models.BooleanField(default=False, verbose_name='Complete')),
            ],
        ),
    ]
